enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
cli-source = "inotia00/revanced-cli" # where to fetch cli from.

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
arch = "arm64-v8a"
included-patches = "'Hide ads' 'Change start page' 'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Dark theme' 'Remove background playback restrictions' 'Bitrate default value' 'Sanitize sharing links' 'Settings for YouTube Music'"
exclusive-patches = true

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
arch = "arm64-v8a"
included-patches = "'Hide ads' 'Hook YouTube Music actions' 'Navigation bar components' 'Change start page' 'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Theme' 'Remove background playback restrictions' 'Bypass URL redirects' 'Sanitize sharing links' 'Settings for YouTube'"
exclusive-patches = true
